name: Learning GitHub Script
on:
  issues:
    types: [opened]
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Comment on new issue
        uses: actions/github-script@0.8.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
             const fs = require('fs')
             const issueBody = fs.readFileSync(".github/ISSUE_RESPONSES/comment.md", "utf8")
             github.issues.createComment({
             issue_number: context.issue.number,
             owner: context.repo.owner,
             repo: context.repo.repo,
             body: issueBody
             })
      - name: Add issue to new GitHub Project (beta)
        if: contains(github.event.issue.labels.*.name, 'bug')
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // 1. Get the ProjectV2 ID (update login and projectNumber as needed)
            const getProjectIdQuery = `
              query($login: String!, $number: Int!) {
                user(login: $login) {
                  projectV2(number: $number) {
                    id
                  }
                }
              }
            `;
            const projectNumber = 1;
            const login = "robin-van-rooij";
            const projectResp = await github.graphql(getProjectIdQuery, { login, number: projectNumber });
            const projectId = projectResp.user.projectV2.id;
      
            // 2. Add the issue to the project
            const issueId = context.payload.issue.node_id;
            const addItemMutation = `
              mutation($projectId:ID!, $contentId:ID!){
                addProjectV2ItemById(input: {projectId: $projectId, contentId: $contentId}) {
                  item {
                    id
                  }
                }
              }
            `;
            await github.graphql(addItemMutation, {
              projectId,
              contentId: issueId
            });
